apiVersion: v1
kind: Pod
metadata:
  name: gitlab01
  labels:
    app: gitlab01
spec:
  containers:
  - name: gitlab01
    image: 10.28.18.13/gitlab/gitlab-ce:9.4.3-ce.0
    ports:
      - containerPort: 80
    volumeMounts: 
      - name: nfs-gitlab01
        mountPath: "/etc/gitlab"
  volumes: 
    - name: nfs-gitlab01
      nfs: 
        server: 10.28.18.13
        path: "/mnt/gitlab"
