apiVersion: v1
kind: Pod
metadata:
  name: redis01
  labels:
    app: redis01
spec:
  containers:
  - name: redis01
    image: redis
    ports:
      - containerPort: 6379
---
apiVersion: v1
kind: Service 
metadata: 
  name: redis01
spec: 
  ports:
  - port: 6379
    targetPort: 6379
  selector: 
    app: redis01
