apiVersion: v1
kind: Pod
metadata:
  name: node01
  labels:
    app: node01
spec:
  containers:
  - name: node01
    image: 10.28.18.13/node_project:v1
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata: 
  name: node01
spec: 
  ports:
  - port: 80
    targetPort: 80
  selector: 
    app: node01
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node01
spec: 
  rules: 
  - host: node01.test.com
    http: 
      paths:
      - path: /
        backend:
          serviceName: node01
          servicePort: 80